version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    restart: always

networks: 
  postgres-compose-network:
    driver: bridge